version: '3.8'

services:
  redis-main:
    image: redis:latest
    container_name: redis-main
    command: redis-server --port 10001
    ports:
      - "10001:10001"
    volumes:
      - redis-main-data:/data
    networks:
      - redis-network

  redis-sub-1:
    image: redis:latest
    container_name: redis-sub-1
    command: redis-server --port 10002 --replicaof redis-main 10001
    ports:
      - "10002:10002"
    depends_on:
      - redis-main
    volumes:
      - redis-sub-1-data:/data
    networks:
      - redis-network

  redis-sub-2:
    image: redis:latest
    container_name: redis-sub-2
    command: redis-server --port 10003 --replicaof redis-main 10001
    ports:
      - "10003:10003"
    depends_on:
      - redis-main
    volumes:
      - redis-sub-2-data:/data
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-main-data:
  redis-sub-1-data:
  redis-sub-2-data:
