version: '3.7'
services:
  redis-master:
    image: redis:7.0
    container_name: redis-master
    ports:
      - "16379:6379"
    command: >
      redis-server 
      --port 6379 
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000
    env_file:
      - .env.redis
    networks:
      - redis-net

  redis-replica:
    image: redis:7.0
    container_name: redis-replica
    ports:
      - "16380:6379"
    command: >
      redis-server 
      --port 6379 
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000
    env_file:
      - .env.redis
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
