redis:
  host: ${REDIS_MAIN_HOST:localhost}
  main:
    port: ${REDIS_MAIN_PORT:6379}
    password: ${REDIS_MAIN_PASSWORD}
  # sub:
  #   port:
  #     - ${REDIS_SUB_PORT_A:}
  #     - ${REDIS_SUB_PORT_B:}
