package app.application.auth;

public enum LoginRefreshRotationStatus {
  ROTATED,
  INVALID_TOKEN,
  TOKEN_EXPIRED,
  SESSION_EXPIRED,
  SESSION_REVOKED,
  REUSED_WITHIN_GRACE,
  REUSE_DETECTED_SESSION_REVOKED,
  USER_INACTIVE_SESSION_REVOKED
}
