### 퀵 모델 비속어를 검증할 수 있다.
POST {{host}}/api/v1/filter
Content-Type: application/json
x-api-key: L7tHdSsKmXCMsZOH5HYWr2LEFZx3DZUHnisS7NfFyHM

{
  "text": "{{text}}",
  "mode": "QUICK"
}

### 노말 모델 비속어를 검증할 수 있다.
POST {{host}}/api/v1/filter
Content-Type: application/json
x-api-key: dsadsads

{
  "text": "{{text}}",
  "mode": "NORMAL"
}

### 필터링 모델 비속어를 검증할 수 있다.
POST {{host}}/api/v1/filter
Content-Type: application/json
x-api-key: dsadsads

{
  "text": "{{text}}",
  "mode": "FILTER"
}
