### 이메일 인증 번호 요청
@email = rlagusrl01234@naver.com
GET {{host}}/api/v1/clients/send-email?email={{email}}

### 이메일 인증 후 API 키 조회
PUT {{host}}/api/v1/clients/send-email
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "601994"
}
