server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  profiles:
    include:
      - rdb
      - redis
      - domain
      - core
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:email@gmail.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000
      mail.starttls.enable: true
      mail.smtp.auth: true

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]
      base-path: ${ACTUATOR_PATH:/health}
