server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  profiles:
    include:
      - rdb
      - redis
      - domain
      - core

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]
      base-path: /system/actuator
