server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  profiles:
    include:
      - rdb
      - redis
      - domain
      - core
  security:
    # Security 설정 추가
    endpoints:
      actuator:
        ip-address-list: 127.0.0.1


management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]
      base-path: /system/actuator
