name: deploy workflow

on:
  pull_request:
    branches:
      - release
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true &&  startsWith(github.event.pull_request.head.ref, 'release-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 프로젝트 복사
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/app/profanity-filter-api
          remote_host: ${{ secrets.DEV_SERVER_IP }}
          remote_port: ${{ secrets.DEV_SERVER_PORT }}
          remote_user: ${{ secrets.DEV_SERVER_USERNAME }}
          remote_key: ${{ secrets.DEV_SSH_KEY }}

      - name: 프로젝트 환경 변수 설정 및 빌드
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/profanity-filter-api
            touch  /home/ubuntu/app/profanity-filter-api/.env
            echo "${{ secrets.ENV }}" > /home/ubuntu/app/profanity-filter-api/.env  
            chmod +x gradlew
            ./gradlew clean build -x test

      - name: 배포 스크립트 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/profanity-filter-api/script
            chmod +x deploy.sh
            ./deploy.sh
